DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  username VARCHAR(250) PRIMARY KEY,
  password VARCHAR(250) NOT NULL
);



DROP TABLE IF EXISTS ITEM;

CREATE TABLE ITEM (
  username VARCHAR(250) PRIMARY KEY,
  title VARCHAR(250) PRIMARY KEY,
  description VARCHAR(250) NOT NULL
);