DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  id LONG PRIMARY KEY;
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);



DROP TABLE IF EXISTS ITEM;

CREATE TABLE ITEM (
  title VARCHAR(250) PRIMARY KEY,
  description VARCHAR(250) NOT NULL
);